problem: CircleCI brew install go at go upgrade
==> Downloading https://homebrew.bintray.com/bottles/go-1.9.4.sierra.bottle.tar.gz

==> Pouring go-1.9.4.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/go
Target /usr/local/bin/go
is a symlink belonging to go. You can unlink it:
  brew unlink go

To force the link and overwrite all conflicting files:
  brew link --overwrite go

To list all files that would be deleted:
  brew link --overwrite --dry-run go

Possible conflicting files are:
/usr/local/bin/go -> /usr/local/Cellar/go/1.9.3/bin/go
/usr/local/bin/godoc -> /usr/local/Cellar/go/1.9.3/bin/godoc
/usr/local/bin/gofmt -> /usr/local/Cellar/go/1.9.3/bin/gofmt
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.9.4: 7,654 files, 294MB

solution: install -f